[profile.default]
src = 'src'
test = 'test'
script = 'script'
out = 'out'
libs = ['lib']
auto_detect_solc = true
bytecode_hash = "none"
optimizer_runs = 1000000

[rpc_endpoints]
base = "${BASEMAINNET_RPC_URL}"
baseSepolia = "${BASESEPOLIA_RPC_URL}"

[etherscan]
baseSepolia = { key = "${ETHERSCAN_API_KEY}"}
base = { key = "${ETHERSCAN_API_KEY}"}